spring:
  docker:
    compose:
      enabled: false

  main:
    allow-bean-definition-overriding: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: jejugudgo
    password: uvwflpcvvrahuvys
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
        transport:
          protocol: smtp
        debug: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://rds-jejugudgo.c1k0gky20mjs.ap-northeast-2.rds.amazonaws.com:3306/jejugudgo?useSSL\=false&allowPublicKeyRetrieval\=true&useUnicode\=true&characterEncoding\=UTF-8
    username: jejugudgo
    password: jejugudgo123!

  data:
    redis:
      port: 6379
      host: 13.124.30.46

  springdoc:
    version: v1.0.0
    default-consumes-media-type: application/json;charset=UTF-8

  secret:
    key: 68a4ef27a3f2f0f605a6781e6be34b466b5da3d11db5384218c407e99e6dcecf3361e1f6def13c78f2deb1e6e822bef2ca1c95b1166c97c5278ad81fdba4538

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            redirect-uri: ${GOOGLE_REDIRECT_URL}
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            scope:
#              - email
#              - profile
#          kakao:
#            client-id: ${KAKAO_REST_API_KEY}
#            redirect-uri: ${KAKAO_REDIRECT_URL}
#            client-secret: ${KAKAO_SECRET_KEY}
#            client-name: Kakao
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_post
#            scope:
#              - account_email
#              - profile_nickname
#              - profile_image
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id

coolsms:
  api:
    key: NCSGT9CA86D62BVL
    secret: ZANS0FUZCRD4THLG8PNFQ8NQLFCML6KV

sendNumber: 01065535378

logging:
  level:
    root:
      info

    org:
      springframework:
        security:
          debug

    web:
      debug

tour:
  api:
    key: Awl7QKVZm9ygqL9hCjkRj4GE%2FrfVqKDmTjoZuuoyl7XiJ1aP041sorWVVCEUw217Z5iCsyhijpOkpYTVJc70Sg%3D%3D
