spring:
  docker:
    compose:
      enabled: ${DOCKER_COMPOSE_ENABLED}
  main:
    allow-bean-definition-overriding: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
        transport:
          protocol: smtp
        debug: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      port: 6379
      host: 127.0.0.1

  springdoc:
    version: v1.0.0
    default-consumes-media-type: application/json;charset=UTF-8

  secret:
    key: ${SECRET_KEY}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${GOOGLE_REDIRECT_URL}
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            redirect-uri: ${KAKAO_REDIRECT_URL}
            client-secret: ${KAKAO_SECRET_KEY}
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - account_email
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


coolsms:
  api:
    key: ${COOLSMS_KEY}
    secret: ${COOLSMS_SECRET_KEY}

sendNumber: ${SEND_NUMBER}

logging:
  level:
    root:
      info

    org:
      springframework:
        security:
          debug

    web:
      debug

tour:
  api:
    key:
      ${TOUR_API_KEY}

public-data:
  api:
    key: ${PUBLIC_DATA_API_KEY}
    base-url: https://api.odcloud.kr/api/15096996/v1/uddi:6738a90c-ec96-4245-a187-9528cea62904
