name: Deploy Spring Application

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Repository Checkout
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up PEM Key
    - name: Set up PEM Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PEM_KEY }}" > ~/.ssh/ec2-key.pem
        chmod 600 ~/.ssh/ec2-key.pem
        ssh-keyscan -H 13.124.30.46 >> ~/.ssh/known_hosts

    # 3. Deploy to EC2
    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/ec2-key.pem ubuntu@13.124.30.46 << 'EOF'
        cd /home/ubuntu/Backend
        git pull origin deploy
        ./gradlew build
        pm2 delete spring_app || true
        pm2 start "java -jar build/libs/jejugudgo-1.2.3-SNAPSHOT.jar" --name spring_app
        EOF
