name: Deploy to EC2

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: environment  # GitHub Environments 이름

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Java 17 설치
          distribution: 'temurin' # OpenJDK 배포판

      - name: Verify Java version
        run: java -version # Java 버전 확인

      - name: Set up environment variables
        env:
          DOCKER_COMPOSE_ENABLED: ${{ vars.DOCKER_COMPOSE_ENABLED }}
          MAIL_ID: ${{ vars.MAIL_ID }}
          MAIL_PASS: ${{ vars.MAIL_PASS }}
          DATASOURCE_URL: ${{ vars.DATASOURCE_URL }}
          DATASOURCE_USERNAME: ${{ vars.DATASOURCE_USERNAME }}
          DATASOURCE_PASSWORD: ${{ vars.DATASOURCE_PASSWORD }}
          REDIS_PORT: ${{ vars.REDIS_PORT }}
          REDIS_HOST: ${{ vars.REDIS_HOST }}
          SECRET_KEY: ${{ vars.SECRET_KEY }}
          COOLSMS_KEY: ${{ vars.COOLSMS_KEY }}
          COOLSMS_SECRET_KEY: ${{ vars.COOLSMS_SECRET_KEY }}
          SEND_NUMBER: ${{ vars.SEND_NUMBER }}
          TOUR_API_KEY: ${{ vars.TOUR_API_KEY }}
        run: echo "Environment variables are set."

      - name: Build application
        run: ./gradlew build
        
      - name: Verify build output
        run: ls -l build/libs

      - name: Upload artifact to EC2
        run: |
          echo "${{ vars.EC2_SSH_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem
          scp -o StrictHostKeyChecking=no -i ec2-key.pem build/libs/jejugudgo-1.2.3-SNAPSHOT.jar ubuntu@13.124.30.46:/home/ubuntu/jejugudgo-1.2.3-SNAPSHOT.jar
      
      - name: Start application on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@13.124.30.46 << EOF
          pm2 stop myapp || true
          pm2 start "java -jar /home/ubuntu/jejugudgo-1.2.3-SNAPSHOT.jar" --name myapp
          pm2 save
          EOF
